name: 'KrazyShulkers'
authors: [Rektb (lMartin3#1975), KrazyxWolf_]
version: ${project.version}
api-version: '1.20.6'
softdepend: [ChestSort, WorldGuard]
main: com.krazy.shulkers.KrazyShulkers
commands:
  ksb:
    description: 'Main KrazyShulkers command'

permissions:
  krazyshulkers.*:
    description: Grants all KrazyShulkers permissions
    children:
      krazyshulkers.use: true
      krazyshulkers.admin: true
      krazyshulkers.bypasscooldown: true
  krazyshulkers.use:
    description: Allows the player to use the plugin's features
  krazyshulkers.admin:
    description: Allows the player to reload the configuration
  krazyshulkers.bypasscooldown:
    description: Allows the player to bypass the established cooldown

